### ISSUE TITLE
Return the concrete type, not the interface

### ISSUE THREAD

**Issue by fernandoocampo** [wilorios/microservice-template-go#1]
This is considered interface pollution, the idea is to discover the interfaces and avoid starting from abstractions.

https://github.com/wilorios/microservice-template-go/blob/d2072ee3833dc08246db87f02dfd59bed637b6af/internal/controller/controller.go#L21

another point here is that the bigger the interface, the weaker the abstraction.

**Comment by wilorios** [comment]
Ok, done, returning the concrete type not the interface,
